#cloud-config
# Create a group
groups:
  - hashicorp

# Create users, in addition to the users provided by default
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+UMhtBaeH9VtTKx4f5h9OdwbMCymUbVxbPLjZdl2iNsTo/TkNfwEVsrYa+rH4U+B5sxDF3yxSIPP7YmRmYUZ6C7BLx55TUFumNN2nJOFqO7UKt5piLI7cmeZal5Dyc/qvzfOMN8p+Yt6jH36sGhXvlhqY52EFRX3q8yP0B3fz8Pobu946cgxSvaDNzMowQ+qL2zC44YlwxQuZXGRUoaiSgv2EfinF/qhqv1KFAGCg2oL8jKOTrGwl30bqN8xnnyb95AFqxmWHXCL3AW6vdNK4p2gaunNOkPCIhtS3A9o1LoPxRJ/BFUUyu6zTewfe6wXX51V/JZndbyHu334JQbCz8C+fz15Zusu3zSjA8Kql48X6RoSMccQm5WGmlbF12SjEPsFcTfOT1h+NX7LMPmD+vcRPzHJBEgAiQhbztKHnvs171iTW16ZyObpsFrRy2RvfVfqDqIhdY4b4dSeD3XR6e23Vtltj5kuDR55Zw4nXWpjwwHM9okDmwYGXAmUpS+0= idimma@hng" # an SSH public key that is authorized
                      # to connect to this account
# Run a few commands (update apt's repo indexes and install curl)
runcmd:
  - sudo apt-get update
  - sudo apt install curl -q -y
  - echo "Done"